
function changeInfo(a){
    let info = [`<link rel="stylesheet" href="mainZ.css"><header><img src="img/logoGarufa.png" height="100%"></header><main><div class='card' onclick="window.open('vino.html')"><img src='img/TA/01.png' width='40px'><ul><li>Gran reserva</li><li><img class="icon" src="img/botella-de-vino.png">$790.00</li><li><img class="icon" src="img/copa-de-vino.png">$790.00</li></ul></div><div class='card' onclick="window.open('vino.html')"><img src='img/TA/02.png' width='40px'><ul><li>Gran reserva</li><li><img class="icon" src="img/botella-de-vino.png">$790.00</li><li><img class="icon" src="img/copa-de-vino.png">$790.00</li></ul></div><div class='card' onclick="window.open('vino.html')"><img src='img/TA/03.png' width='40px'><ul><li>Gran reserva</li><li><img class="icon" src="img/botella-de-vino.png">$790.00</li><li><img class="icon" src="img/copa-de-vino.png">$790.00</li></ul></div><div class='card' onclick="window.open('vino.html')"><img src='img/TA/04.png' width='40px'><ul><li>Gran reserva</li><li><img class="icon" src="img/botella-de-vino.png">$790.00</li><li><img class="icon" src="img/copa-de-vino.png">$790.00</li></ul></div><div class='card' onclick="window.open('vino.html')"><img src='img/TA/05.png' width='40px'><ul><li>Gran reserva</li><li><img class="icon" src="img/botella-de-vino.png">$790.00</li><li><img class="icon" src="img/copa-de-vino.png">$790.00</li></ul></div><div class='card' onclick="window.open('vino.html')"><img src='img/TA/06.png' width='40px'><ul><li>Gran reserva</li><li><img class="icon" src="img/botella-de-vino.png">$790.00</li><li><img class="icon" src="img/copa-de-vino.png">$790.00</li></ul></div></main><footer>Un momento para compartir</footer>`,
    `0`];
    document.getElementById("body").innerHTML = info[a];
}
function crear(){
    let info = [`<link rel="stylesheet" href="mainM.css"><header><img src="img/logoGarufa.png" height="100%"></header><aside></aside><nav><div onclick="changeInfo(0)">Vinos Zacatecanos</div><div onclick="changeInfo(1)">Vinos Mexicanos</div><div onclick="changeInfo(2)">Vinos Argentinos</div><div onclick="changeInfo(2)">Vinos Chilenos</div><div onclick="changeInfo(2)">Vinos Españoles</div><div onclick="changeInfo(2)">Vinos Franceses</div><div onclick="changeInfo(2)">Vinos Italianos</div><div onclick="changeInfo(2)">Vinos Blancos</div><div onclick="changeInfo(2)">Vinos Rosados</div><div onclick="changeInfo(2)">Vinos Espumosos</div></nav><footer>Un momento para compartir</footer>`,
    `0`];
    document.getElementById("body").innerHTML = info[0];
}
